# Generated by Django 5.1.6 on 2025-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=512)),
                ('experiences', models.TextField()),
                ('Service', models.CharField(max_length=512)),
                ('is_available', models.BooleanField()),
                ('is_verified', models.BooleanField()),
            ],
        ),
    ]
