# Generated by Django 5.1.7 on 2025-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_photo', models.ImageField(default='images/profil photo.jpg', upload_to='images/')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('gender', models.CharField(default='M', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_photo', models.ImageField(default='images/profil photo.jpg', upload_to='images/')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('gender', models.CharField(default='M', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('experiences', models.TextField()),
                ('service', models.CharField(max_length=100)),
                ('Volunteering_site', models.CharField(default='The holy mosque', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('ratings', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
