# Generated by Django 5.1.7 on 2025-04-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
    ]
