# Generated by Django 5.1.7 on 2025-04-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_gender_volunteer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='ratings',
            field=models.SmallIntegerField(default=0),
        ),
    ]
