# Generated by Django 5.1.7 on 2025-04-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_volunteer_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Service',
            new_name='service',
        ),
    ]
